### ISSUE TITLE
TypeError: error.match is not a function

### ISSUE THREAD

**Issue by ppisljar** [elastic/makelogs#30]
When runing makelogs with latest master of kibana (and es provided with npm run elasticsearch)
an exception is thrown

```
$ makelogs
Generating 14000 events from 2016-12-22T00:00:00Z to 2016-12-24T23:59:59Z
? Existing logstash-* indices and/or index templates were found, can they be replaced? Yes
clearing existing "logstash-*" index templates and indices
creating index template for "logstash-*"
TypeError: error.match is not a function
    at /home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/eventBuffer/_bulkQueue.js:45:23
    at Array.forEach (native)
    at /home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/eventBuffer/_bulkQueue.js:37:20
    at tryCatcher (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
undefined
TypeError: error.match is not a function
    at /home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/eventBuffer/_bulkQueue.js:45:23
    at Array.forEach (native)
    at /home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/eventBuffer/_bulkQueue.js:37:20
    at tryCatcher (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/promise.js:584:18)
    at Async._drainQueue (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/ppisljar/.nvm/versions/node/v6.4.0/lib/node_modules/makelogs/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

```

**Comment by spalger** [comment]
Is this till happening @ppisljar?

**Comment by spalger** [comment]
I'm unable to reproduce

**Comment by ppisljar** [comment]
can't reproduce anymore either ... closing
